# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

# workflows:
#     ios-app:
#         name: iOS App
#         environment:
#             vars:
#                 XCODE_WORKSPACE: "ahorta"
#                 XCODE_SCHEME: "ahorta"
#             xcode: latest
#             cocoapods: default
#         scripts:
#             - xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#         artifacts:
#             - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
#             - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

            workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      vars:
        XCODE_WORKSPACE: "ahorta.xcworkspace"  # PUT YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "ahorta" # PUT THE NAME OF YOUR SCHEME HERE
        APP_STORE_CONNECT_ISSUER_ID: "Encrypted(Z0FBQUFBQmdMWUtmUmxHVVg1VFM4WFdycEw2V1ZlcmhMeG1Yb0FaaE1WZVczRWs2aU9KZU96VU00REZRWTJqV1k4enBHX0RnNDlBTHJ6bkRlV0ZTNGlnUE43X2dibmlmSDNBWnJRSUFGVXNJQWR6TUxsZWlZMElWdElralpwMmIwX0hhYjQwU3lwRjg=)"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "Encrypted(Z0FBQUFBQmdMWU1rSEZ3cjBXLTROYjRqWmVRNmR2ZW84eW52RlhyMWJFelM5bTNmai00TnhFcFVoSm9kbng2U1hNalhwV3JEcEdaZEZGZ0haeVFlUzRrNW5wUHF1MzZDY0E9PQ==)"
        APP_STORE_CONNECT_PRIVATE_KEY: "Encrypted(Z0FBQUFBQmdMWVBvWmdVMmxlb0dxRUZPNWp3WFVXOVlPVjk0ZGFva3hRUE9scjJWNF9EcW1pbEVFbTA1eW9xQldxTUYxT0NvOVVsT0plYVVGbkJ2bUdxZ3Z4VElTZW9FZm5HLWNmLTJLWGY3ZmVOSkU1YUVVdGpYdjBxdElrc3lnWEVCc2xNN1gtVEhPRXZpc2V5cHF6VEdCQjR1SUs0T2xuaWMwanpkNU01cmN4U0NlNldacUR2ZG5KUjkxemJObWhOYUFTd05mQ0s2dmc4RXFzRmlqSVZjTk9wRGFsM19fc2NFTm1URGhrdk02bk9RSkRIaXRNa2g5dFlrUjAxX2l0aVRCWFNLaEFqOFZVMHF6cXpiSGtYZWJHTjlxSEx4OGFnaDJUcjJDUVNvN2EwU3JPWEJ0X2ZQQUwyei1tVHktaXBCWWdtZzRuMjV4bW5DM1RzN3BkLVVKOHRhQmIwNWd3PT0=)"
        CERTIFICATE_PRIVATE_KEY: "Encrypted(Z0FBQUFBQmdMWVRmYk9mb2Ntc2dMLVpyV2U5aURfOTk2STNrY0tQY21uMW1EanNyVTVNNWxRZFZaeVZNZWxYWGNNc3VFbHhsTjM0X0hheXRsMGx2UF9jYy1rNEpmbzBQRTJzT1NvOF9lOGNmV3RmQ3JqSjRhUF9xbGRWVFlVd29DNEtRYlBHUzRHRVI5SW9IVXl0X2lnQ1hkS3hOZERUbEdnRkFuSlJGVW5ocXBRNGRELXl6cVRiZDhqLUZGV3lLbE1HTDl2Z2U3N1ZiZkZ3bVB1X3RvWG1jMWlzeEpMbi01eHlfWDRhSWltSHRKVTBZMUFLM1h2V2s2U09ia2RmVjJHdVlwYnQyYUNKLXVMdWE4bGhJeGNOMEFqVHhBazFPdFdyOE5wbXB2amlIRnRZeWxIal9NYlNHVkllcUQ2SmtQRlRtLWFpT2RkNklwbGQ5VU5CSEtPVjVjdW1DUHY2MTBUTFlXMk5BUkdNcXZ4MmloVXVuclE0TG1YZ1dKQlNXa25wb0taUklRUDZGQnpYTFdCQzJkdk5wUTdfVW1vZXEySUtFMFNiTTA0VXpOZHJDcFhOSzlvcG1XbTVnWXNIRWY4dVE2bjBPWWNJTmhFMm9ickV2d1dsY015UGd1T3A2SlhMWDgwamFYV0tEaE83dmNaNThZU2x4MXlHTThwQXlhYUFKMUU1ZlNjTHVPT0Jra0hGbEZ5WDdQMXdlN0hfck5hdWNvN0lFb1Z4aXI0Y09EZzJqLXZwbXFqZjJ1RU9kZWxvV2dZZ0VWbV9MRzdZNzJaMXB6elE2d1JtM3Uzc0o4cklqUUNYOGEyVnpvV19mc1hBZ2diOWpDTjBDNnBTa1hubENvN053RVhJTkN0ZjVTV01FU1BiV1dqb3k2eHhEbm5SbTBaS1k2SUNTQkVCZk1GeFFZZmRTOFNRWjlkcC1NbmpKMXREeXRIQnk0ajk3LU9UMGJsM0lYZnJDRUFrR3FJMVFKZkVfbGRGSU9VZy14dnE0TDBQTzhaTDY0NU1LOWI1V0lfN285R1A2WTNQazhuTVp5Z1IwVFNjMGQyYi1fMUFRbDhiU1pGOG93OG84bWFmeU0wTlNHSVRwdjI3UFAwXzl3c05pVVZmVDFvdm84elhBTE1COUJocVdmSldxQzJEN1dlNjZGMGxyS0puRVNSN0g0TUhMb0pscVJVTWVBVTlNa2o0Qm1uZ2NCQkY2aGNVLXFneF8xelFyVXE1eHNVVGxiRElaY2VlaTBBaVZLWTFJNERjUjhZUXpIYmhwUmxqQmM1clhYc1psaER6TTUtOXRMalhfRUZUTEhMTHNWM2ljUG9JVUgwdkFKUlBsSFBTR1BtYmFmOG5xdGZFZ2w4LVZrQ3ZZMDJ3SUtvMmFzaFhMTktIdWVSNlVaaUFXR2x4TzV3OGZGUThlRjRiSjBLN2xjd1prU3MwV28xRE9FWFQ4b3lPV1JSazRLNlVDN3F2NEdpRkQ5b1ZnaWExM0I2dlp3MHFlN2xLOVVyVHhXSGtMVXpJTk41aEpVRFpDMDFQemFycTczeHFHQ3FQSWxhTmxORnB0N3JhaFN2MjZsRnBwSkt5TWNXZVdrWFR1NWNwaVpSb2JNZmQySl9YMXF3bXdUNWEwNUlTaUxUQUpfS2tQczQ2TlRzWlFpTHNQOHViLV9PdVZLQWhtZWJndGp1eEhndFpjcDQzSWY5TmRWVUpkaU9jNTFoMHRTVXBnY1Y2RmpOVlIzQUZXbl9fMGlDdTREY0xPUWVyM3RQR0NjdkZoUnFGaENsUTh5Q3FXT21ES1FVWFM0Ynp1YzlaNVJudVdieURnUUlrQVczQ3F3VllGX3lKTzk4b1lEeXU3d3V0NFpBRG5GbHpHbzR5WWEydW13NWotdHVfbW1pMTRJVlJQSE5CZmVTRWZVTXlnb1hRbDJwMjcweGF0YTNUT1ZDVzA1bzBmOGZIVjBrZXpuZmtCSHFvSnFja3A0WTN4S2F0MkpGZklfMG1jTU84QjdZMU9PYW45NjlhaUtyY19yc2FCVGlQM0k1N1h6OGJmeXFrNm1vUFlXeGUydEV5MFlVTDBNNW8xbU0xSzVDTWw3emRQb1g5dThaZ3I3c1RXbmRJbS1xMlBYM3lLTVhiVElOc2VKeHB0OGp3UWFQWlQtRnFWVW9uRzN5UFBZajlzR3BURnE5ZlJNZy1jVlZESms1Y3B4OXFjNlJTV2tBbERGZUstVEdGWGRlTjJ5TnNpNGJjU3ZLLUs0bHJWSUJxbURFanBxcWstYzh4d0ZoQmNXVnlqMm9id3VYN19EYXoxaDBvTkZDcTNsZmRZOEYxZzdldkJ2ZkNaUGRxXzl2YTUtbVI2dmdHSFZGU2FnQldETWJGV05sb3hSd2NlVmp5TlV3TXRzZWdtMHA0cUQ0SVlfelBPUlZTT3gyYm11Q0wwdFJVR01ZQjJXNmdDS0xOWU16aTVhTmZUd3RyY1RWQUNTcjV1YWVtVUtxa21wd0lmN29WSWZlcWJqRUcwSGowUFdjcWF1SGhfQ1I5cGpsSWJUTkpGaWhlTV84cUIxckNiSUo2Um42ZWFfMXZMaHBNbjF1eHR1MGoyb29EbjBVLUR1MnVZVFJBVWczNVNKMTFHZVEzeWQ4cWJ1NXZpbFJnS1l6SHdqdld5NTBBdjNEMC1FX3NNOTZESnVnZTlHR1M1ZU4ya05aQXROakFtTGV6RkRMb0FSbkJ0cXhfeDAxWFo4WlktWVJQQ1JfOHVFWUdZTWItRXM5ODRSV2x3aHNOUkpOZXZCSkNYcUhqZGN2azQ4NkFvNTRGcjFmU1JzU2ctZ2Q0NmhXeEJ3WG9OWlktZG1pNEduV1BfeXBQclhWcWIxNGZQN3hwV2VRM2l2UHI0WTJ1TFpYVjdGZVcwQXRvamtvZUpmSjhhZ3k4OU1keEgwNXk2a0tmZEhMLTkwQTNOTFZBc3FWb1kzTDg4TVlUZDdXSnpIM2RPQkNoWldtLTVhczdmc1VSa2tlTWxMOWl4cTFXN0lJTkF6b0tzMm1sajFUN3ZnMnBwajFFWVYwdTZldXhpVV9WVkpLZV84aEtxWldxeFFRa0Y5SnNqUUhPNWE2R2pRWnlmVXpYUnlyMFhESlhYZElvUlc4Ul83WkFDTE9oSU1BSU9Id2ZseUlaSjJ6UUhpSzRNbWVndTB6UlNrdldrTEpLZjdEeWUydnhsTVlSOWZXRy04RGdRT0pManhLNnEtTHVQMjV1MXFtWGNxdVVHT0cxbk8talhtWXVQQ1dSQzQwUDNzajlkZFRtdzgtY3hOMlZXSldCcU0wLXhFMWtpb3FzWlhaYWc1WTBVUTN2QU0wYm5OcjNRb0tVZ1RTN0l4Wk1INUJIcjc2ZVJCLTlOYU5LUy1hVF82S1pDd1RYX2dDR1pEZEItWEhZcnRILWM4TXc5LXpoYnZEb1lpMFpZVXRQcnR3SGZVZ3hMSlJwLU5WRnQ0cjl1YW1tSW9iZ3hKT3R2Y0RLUlA4MEREelFGUnJfaTVwMzFkaDI4QjFOSm5iUERLQ0NlbkY4aGFHaUJydmpoUTY0aVd0d0owc3otbjNGS2ZQUC1HdnhwQXBJLWlhemFFR1ZxMl9tRzhIMFR1UVlMNkE2QUljODJiOHV0NHRuSk1NZjRvR1JmVkhoRlA0TTN4aWVONzF0UnpFTV82OXZRRHRTZEJMQ1duUEJOT3dQSEp0b01aOWM1bEp6UjFpQ1N2dDBVc0VWQ1hwalp0Nm9pSkpyYjh5dUZtYVkxd3pLS3Jxd3RNVmZYV3pyMHhOQS01UEI4ekF4VmJnZVVQd1RNcDVSSHBLYlg3Wk9pYms5VDloRzd3RDVZYVItUEhQQkRPV3B4YU8wOE9VMXFfWk1IaW93NXBDSmFPYmtkV2ZkbnMyRlRBZF9hM3JfWmNUT0ZFR0JJc0pEazlZOEJSNnk3dVhramE4YjBKMWRUWWJILU5KWkpZenZIakZuY3hsWmpjNWNUd21UeDBaM01WVUJWUWdfdDVLR28xam5xdW5ERjNrUy1lbTZTSG5NbFRVYjRTckNvbVFMOFVCbDJBTlhqYkxjWjdCMWNxYlh1Mkx3PQ==)"
          
        # FCI_CERTIFICATE: Encrypted(...) # PUT THE ENCRYPTED DISTRIBUTION CERTIFICATE HERE
        # FCI_CERTIFICATE_PASSWORD: Encrypted(...) # PUT THE ENCRYPTED CERTIFICATE PASSWORD HERE
        # FCI_PROVISIONING_PROFILE: Encrypted(...) # PUT THE ENCRYPTED PROVISIONING PROFILE HERE
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      # - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      #   script: keychain initialize
      # - name: Set up Provisioning profiles from environment variables
      #   script: |
      #     PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
      #     mkdir -p "$PROFILES_HOME"
      #     PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
      #     echo ${FCI_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
      #     echo "Saved provisioning profile $PROFILE_PATH"          
      # - name: Set up signing certificate
      #   script: |
      #     echo $FCI_CERTIFICATE | base64 --decode > /tmp/certificate.p12
      #     keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $FCI_CERTIFICATE_PASSWORD          
      # - name: Increment build number
      #   script: agvtool new-version -all $(($BUILD_NUMBER +1))
      # - name: Set up code signing settings on Xcode project
      #   script: xcode-project use-profiles
        name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: |
            $(xcode-project detect-bundle-id)
            --type IOS_APP_DEVELOPMENT \  # Specify provisioning profile type*
            --create  # Allow creating resources if existing are not found.      
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        apple_id: apple_id: diwoapple@gmail.com 
        password: Encrypted(Z0FBQUFBQmdMamdCcW12WWFraW9wUURWXzVPM0Z3cUxGazJfWXRCMjZhOHJtTmFVMWxELUxuWUNZSGNZNFpHSGhIY3kybWtvdHdqWjRPS3hoRk9Rc181YUpTbUU3aHR4MnhUdTNyV2RqTzJGdW9EbmQzQi1fRDA9) # PUT YOUR APP-SPECIFIC-PASSWORD HERE https://support.apple.com/en-us/HT204397
